=== dillonyost/qball-unc/examples/MgO216/species.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
  targetNamespace="http://www.quantum-simulation.org/ns/fpmd/fpmd-1.0"
  xmlns:fpmd="http://www.quantum-simulation.org/ns/fpmd/fpmd-1.0">
  
  <annotation>
    <documentation> $Id: species.xsd,v 1.6 2008/03/07 20:05:31 fgygi Exp $
      http://www.quantum-simulation.org
      FPMD atomic species XML Schema specification. 
      Copyright (c) 2006-2008 The Regents of the University of California.
    </documentation>
  </annotation>
  
  <element name="species" type="fpmd:speciesType"/>
  
  <complexType name="speciesType">
    <sequence minOccurs="0">
      <element name="description" type="string" minOccurs="0" maxOccurs="1"/>
      <element name="symbol" type="NMTOKEN"/>
      <element name="atomic_number" type="nonNegativeInteger"/>
      <element name="mass" type="fpmd:positiveDouble"/>
      <element name="norm_conserving_pseudopotential" minOccurs="0" maxOccurs="1"
       type="fpmd:norm_conserving_pseudopotentialType"/>
    </sequence>
    <attribute name="name" type="NMTOKEN" use="optional"/>
    <attribute name="href" type="anyURI" use="optional"/>
  </complexType>
  
  <complexType name="norm_conserving_pseudopotentialType">
    <sequence>
      <element name="valence_charge" type="nonNegativeInteger"/>
      <element name="lmax" type="nonNegativeInteger"/>
      <element name="llocal" type="nonNegativeInteger"/>
      <element name="nquad" type="nonNegativeInteger"/>
      <element name="rquad" type="fpmd:nonNegativeDouble"/>
      <element name="mesh_spacing" type="fpmd:positiveDouble"/>
      <element name="projector" minOccurs="1" maxOccurs="unbounded">
        <complexType>
          <sequence>
            <element name="radial_potential">
              <simpleType>
                <list itemType="double"/>
              </simpleType>
            </element>
            <element name="radial_function" minOccurs="0">
              <simpleType>
                <list itemType="double"/>
              </simpleType>
            </element>
          </sequence>
          <attribute name="l" type="nonNegativeInteger" use="required"/>
          <attribute name="size" type="positiveInteger" use="required"/>
        </complexType>
      </element>
    </sequence>
  </complexType>
  
  <simpleType name="positiveDouble">
    <restriction base="double">
      <minExclusive value="0"/>
    </restriction>
  </simpleType>
  
  <simpleType name="nonNegativeDouble">
    <restriction base="double">
      <minInclusive value="0"/>
    </restriction>
  </simpleType>
  
</schema>

=== dillonyost/qball-unc/testsuite/09_nenon_bhs/Ne_BHS_LDA-1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<fpmd:species xmlns:fpmd="http://www.quantum-simulation.org/ns/fpmd/fpmd-1.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.quantum-simulation.org/ns/fpmd/fpmd-1.0
  species.xsd">
<description>
 Generated by bhs on 2012-10-19T14:47:15Z
 Parameters from Bachelet, Hamann, Schlueter PRB26, 4199 (1982)
 Ne Za=10 Zv=8 alpha_loc[]=29.13 11.58 c_loc[]=1.3711 -0.3711
 lmax=2
 l=0 alpha[]= 17.61 20.97 26.47
     c[]= -3.4264 0.6156 0.0747 0.1241 0.007 -0.0226
 l=1 alpha[]= 16.05 17.66 45.22
     c[]= 0.4077 0.1726 -0.2057 0.1283 -0.056 0.0054
 l=2 alpha[]= 9.17 11.32 12.33
     c[]= -1.4102 -0.8951 -0.1337 -0.0911 0.0255 0.045
</description>
<symbol>Ne</symbol>
<atomic_number>10</atomic_number>
<mass>20.1797</mass>
<norm_conserving_pseudopotential>
<valence_charge>8</valence_charge>
<lmax>2</lmax>
<llocal>0</llocal>
<nquad>7</nquad>
<rquad>1.5</rquad>
<mesh_spacing>0.01</mesh_spacing>
<projector l="0" size="800">
<radial_potential>
0.71222390
0.72052624
0.74457726
0.78186280
0.82836770
0.87882350
0.92702703
0.96620455
0.98939372
0.98981492
0.96120586
0.89809781
0.79601799
0.65160998
0.46267156
0.22811668
-0.05212557
-0.37725777
-0.74578679
-1.15570207
-1.60464074
-2.09002432
-2.60915606
-3.15927375
-3.73755781
-4.34110007
-4.96684246
-5.61149812
-6.27146865
-6.94277146
-7.62098951
-8.30125340
-8.97826209
-9.64634469
-10.29956189
-10.93184173
-11.53714178
-12.10962697
-12.64385193
-13.13493590
-13.57871934
-13.97189302
-14.31209236
-14.59795268
-14.82912351
-15.00624290
-15.13087498
-15.20541605
-15.23297569
-15.21724060
-15.16232861
-15.07264063
-14.95271721
-14.80710553
-14.64024138
-14.45634944
-14.25936355
-14.05286776
-13.84005757
-13.62371987
-13.40622963
-13.18956066
-12.97530767
-12.76471677
-12.55872163
-12.35798294
-12.16292879
-11.97379436
-11.79065941
-11.61348258
-11.44213194
-11.27641127
-11.11608214
-10.96088191
-10.81053791
-10.66477811
-10.52333890
-10.38597033
-10.25243928
-10.12253108
-9.99604982
-9.87281791
-9.75267490
-9.63547605
-9.52109072
-9.40940063
-9.30029826
-9.19368533
-9.08947143
-8.98757283
-8.88791149
-8.79041416
-8.69501171
-8.60163858
-8.51023228
-8.42073305
-8.33308362
-8.24722893
-8.16311600
-8.08069379
-7.99991307
-7.92072638
-7.84308791
-7.76695346
-7.69228036
-7.61902745
-7.54715502
-7.47662473
-7.40739959
-7.33944390
-7.27272323
-7.20720433
-7.14285510
-7.07964458
-7.01754285
-6.95652104
-6.89655124
-6.83760650
-6.77966079
-6.72268892
-6.66666656
-6.61157018
-6.55737700
-6.50406501
-6.45161288
-6.39999999
-6.34920634
-6.29921259
-6.25000000
-6.20155039
-6.15384615
-6.10687023
-6.06060606
-6.01503759
-5.97014925
-5.92592593
-5.88235294
-5.83941606
-5.79710145
-5.75539568
-5.71428571
-5.67375887
-5.63380282
-5.59440559
-5.55555556
-5.51724138
-5.47945205
-5.44217687
-5.40540541
-5.36912752
-5.33333333
-5.29801325
-5.26315789
-5.22875817
-5.19480519
-5.16129032
-5.12820513
-5.09554140
-5.06329114
-5.03144654
-5.00000000
-4.96894410
-4.93827160
-4.90797546
-4.87804878
-4.84848485
-4.81927711
-4.79041916
-4.76190476
-4.73372781
-4.70588235
-4.67836257
-4.65116279
-4.62427746
-4.59770115
-4.57142857
-4.54545455
-4.51977401
-4.49438202
-4.46927374
-4.44444444
-4.41988950
-4.39560440
-4.37158470
-4.34782609
-4.32432432
-4.30107527
-4.27807487
-4.25531915
-4.23280423
-4.21052632
-4.18848168
-4.16666667
-4.14507772
-4.12371134
-4.10256410
-4.08163265
-4.06091371
-4.04040404
-4.02010050
-4.00000000
-3.98009950
-3.96039604
-3.94088670
-3.92156863
-3.90243902
-3.88349515
-3.86473430
-3.84615385
-3.82775120
-3.80952381
-3.79146919
-3.77358491
-3.75586854
-3.73831776
-3.72093023
-3.70370370
-3.68663594
-3.66972477
-3.65296804
-3.63636364
-3.61990950
-3.60360360
-3.58744395
-3.57142857
-3.55555556
-3.53982301
-3.52422907
-3.50877193
-3.49344978
-3.47826087
-3.46320346
-3.44827586
-3.43347639
-3.41880342
-3.40425532
-3.38983051
-3.37552743
-3.36134454
-3.34728033
-3.33333333
-3.31950207
-3.30578512
-3.29218107
-3.27868852
-3.26530612
-3.25203252
-3.23886640
-3.22580645
-3.21285141
-3.20000000
-3.18725100
-3.17460317
-3.16205534
-3.14960630
-3.13725490
-3.12500000
-3.11284047
-3.10077519
-3.08880309
-3.07692308
-3.06513410
-3.05343511
-3.04182510
-3.03030303
-3.01886792
-3.00751880
-2.99625468
-2.98507463
-2.97397770
-2.96296296
-2.95202952
-2.94117647
-2.93040293
-2.91970803
-2.90909091
-2.89855072
-2.88808664
-2.87769784
-2.86738351
-2.85714286
-2.84697509
-2.83687943
-2.82685512
-2.81690141
-2.80701754
-2.79720280
-2.78745645
-2.77777778
-2.76816609
-2.75862069
-2.74914089
-2.73972603
-2.73037543
-2.72108844
-2.71186441
-2.70270270
-2.69360269
-2.68456376
-2.67558528
-2.66666667
-2.65780731
-2.64900662
-2.64026403
-2.63157895
-2.62295082
-2.61437908
-2.60586319
-2.59740260
-2.58899676
-2.58064516
-2.57234727
-2.56410256
-2.55591054
-2.54777070
-2.53968254
-2.53164557
-2.52365931
-2.51572327
-2.50783699
-2.50000000
-2.49221184
-2.48447205
-2.47678019
-2.46913580
-2.46153846
-2.45398773
-2.44648318
-2.43902439
-2.43161094
-2.42424242
-2.41691843
-2.40963855
-2.40240240
-2.39520958
-2.38805970
-2.38095238
-2.37388724
-2.36686391
-2.35988201
-2.35294118
-2.34604106
-2.33918129
-2.33236152
-2.32558140
-2.31884058
-2.31213873
-2.30547550
-2.29885057
-2.29226361
-2.28571429
-2.27920228
-2.27272727
-2.26628895
-2.25988701
-2.25352113
-2.24719101
-2.24089636
-2.23463687
-2.22841226
-2.22222222
-2.21606648
-2.20994475
-2.20385675
-2.19780220
-2.19178082
-2.18579235
-2.17983651
-2.17391304
-2.16802168
-2.16216216
-2.15633423
-2.15053763
-2.14477212
-2.13903743
-2.13333333
-2.12765957
-2.12201592
-2.11640212
-2.11081794
-2.10526316
-2.09973753
-2.09424084
-2.08877285
-2.08333333
-2.07792208
-2.07253886
-2.06718346
-2.06185567
-2.05655527
-2.05128205
-2.04603581
-2.04081633
-2.03562341
-2.03045685
-2.02531646
-2.02020202
-2.01511335
-2.01005025
-2.00501253
-2.00000000
-1.99501247
-1.99004975
-1.98511166
-1.98019802
-1.97530864
-1.97044335
-1.96560197
-1.96078431
-1.95599022
-1.95121951
-1.94647202
-1.94174757
-1.93704600
-1.93236715
-1.92771084
-1.92307692
-1.91846523
-1.91387560
-1.90930788
-1.90476190
-1.90023753
-1.89573460
-1.89125296
-1.88679245
-1.88235294
-1.87793427
-1.87353630
-1.86915888
-1.86480186
-1.86046512
-1.85614849
-1.85185185
-1.84757506
-1.84331797
-1.83908046
-1.83486239
-1.83066362
-1.82648402
-1.82232346
-1.81818182
-1.81405896
-1.80995475
-1.80586907
-1.80180180
-1.79775281
-1.79372197
-1.78970917
-1.78571429
-1.78173719
-1.77777778
-1.77383592
-1.76991150
-1.76600442
-1.76211454
-1.75824176
-1.75438596
-1.75054705
-1.74672489
-1.74291939
-1.73913043
-1.73535792
-1.73160173
-1.72786177
-1.72413793
-1.72043011
-1.71673820
-1.71306210
-1.70940171
-1.70575693
-1.70212766
-1.69851380
-1.69491525
-1.69133192
-1.68776371
-1.68421053
-1.68067227
-1.67714885
-1.67364017
-1.67014614
-1.66666667
-1.66320166
-1.65975104
-1.65631470
-1.65289256
-1.64948454
-1.64609053
-1.64271047
-1.63934426
-1.63599182
-1.63265306
-1.62932790
-1.62601626
-1.62271805
-1.61943320
-1.61616162
-1.61290323
-1.60965795
-1.60642570
-1.60320641
-1.60000000
-1.59680639
-1.59362550
-1.59045726
-1.58730159
-1.58415842
-1.58102767
-1.57790927
-1.57480315
-1.57170923
-1.56862745
-1.56555773
-1.56250000
-1.55945419
-1.55642023
-1.55339806
-1.55038760
-1.54738878
-1.54440154
-1.54142582
-1.53846154
-1.53550864
-1.53256705
-1.52963671
-1.52671756
-1.52380952
-1.52091255
-1.51802657
-1.51515152
-1.51228733
-1.50943396
-1.50659134
-1.50375940
-1.50093809
-1.49812734
-1.49532710
-1.49253731
-1.48975791
-1.48698885
-1.48423006
-1.48148148
-1.47874307
-1.47601476
-1.47329650
-1.47058824
-1.46788991
-1.46520147
-1.46252285
-1.45985401
-1.45719490
-1.45454545
-1.45190563
-1.44927536
-1.44665461
-1.44404332
-1.44144144
-1.43884892
-1.43626571
-1.43369176
-1.43112701
-1.42857143
-1.42602496
-1.42348754
-1.42095915
-1.41843972
-1.41592920
-1.41342756
-1.41093474
-1.40845070
-1.40597540
-1.40350877
-1.40105079
-1.39860140
-1.39616056
-1.39372822
-1.39130435
-1.38888889
-1.38648180
-1.38408304
-1.38169257
-1.37931034
-1.37693632
-1.37457045
-1.37221269
-1.36986301
-1.36752137
-1.36518771
-1.36286201
-1.36054422
-1.35823430
-1.35593220
-1.35363790
-1.35135135
-1.34907251
-1.34680135
-1.34453782
-1.34228188
-1.34003350
-1.33779264
-1.33555927
-1.33333333
-1.33111481
-1.32890365
-1.32669983
-1.32450331
-1.32231405
-1.32013201
-1.31795717
-1.31578947
-1.31362890
-1.31147541
-1.30932897
-1.30718954
-1.30505710
-1.30293160
-1.30081301
-1.29870130
-1.29659643
-1.29449838
-1.29240711
-1.29032258
-1.28824477
-1.28617363
-1.28410915
-1.28205128
-1.28000000
-1.27795527
-1.27591707
-1.27388535
-1.27186010
-1.26984127
-1.26782884
-1.26582278
-1.26382306
-1.26182965
-1.25984252
-1.25786164
-1.25588697
-1.25391850
-1.25195618
-1.25000000
-1.24804992
-1.24610592
-1.24416796
-1.24223602
-1.24031008
-1.23839009
-1.23647604
-1.23456790
-1.23266564
-1.23076923
-1.22887865
-1.22699387
-1.22511485
-1.22324159
-1.22137405
-1.21951220
-1.21765601
-1.21580547
-1.21396055
-1.21212121
-1.21028744
-1.20845921
-1.20663650
-1.20481928
-1.20300752
-1.20120120
-1.19940030
-1.19760479
-1.19581465
-1.19402985
-1.19225037
-1.19047619
-1.18870728
-1.18694362
-1.18518519
-1.18343195
-1.18168390
-1.17994100
-1.17820324
-1.17647059
-1.17474302
-1.17302053
-1.17130307
-1.16959064
-1.16788321
-1.16618076
-1.16448326
-1.16279070
-1.16110305
-1.15942029
-1.15774240
-1.15606936
-1.15440115
-1.15273775
-1.15107914
-1.14942529
-1.14777618
-1.14613181
-1.14449213
-1.14285714
-1.14122682
-1.13960114
-1.13798009
-1.13636364
-1.13475177
-1.13314448
-1.13154173
-1.12994350
-1.12834979
-1.12676056
-1.12517581
-1.12359551
-1.12201964
-1.12044818
-1.11888112
-1.11731844
-1.11576011
-1.11420613
-1.11265647
-1.11111111
-1.10957004
-1.10803324
-1.10650069
-1.10497238
-1.10344828
-1.10192837
-1.10041265
-1.09890110
-1.09739369
-1.09589041
-1.09439124
-1.09289617
-1.09140518
-1.08991826
-1.08843537
-1.08695652
-1.08548168
-1.08401084
-1.08254398
-1.08108108
-1.07962213
-1.07816712
-1.07671602
-1.07526882
